# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QLabel, QApplication


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 589)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 762, 526))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 41, 16))
        self.label_3.setObjectName("label_3")
        self.start = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.start.setGeometry(QtCore.QRect(260, 430, 81, 31))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setObjectName("start")
        self.check_cookie = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.check_cookie.setGeometry(QtCore.QRect(450, 430, 91, 31))
        self.check_cookie.setObjectName("check_cookie")
        self.header_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.header_2.setGeometry(QtCore.QRect(80, 170, 681, 141))
        self.header_2.setObjectName("header_2")
        self.datas = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.datas.setGeometry(QtCore.QRect(80, 80, 681, 81))
        self.datas.setObjectName("datas")
        self.url = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.url.setGeometry(QtCore.QRect(80, 20, 681, 41))
        self.url.setObjectName("url")
        self.post = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.post.setGeometry(QtCore.QRect(90, 320, 71, 21))
        self.post.setObjectName("post")
        self.encode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.encode.setGeometry(QtCore.QRect(440, 320, 61, 21))
        self.encode.setObjectName("encode")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(390, 321, 72, 20))
        self.label_4.setObjectName("label_4")
        self.verify = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.verify.setGeometry(QtCore.QRect(150, 320, 71, 21))
        self.verify.setObjectName("verify")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(90, 360, 31, 20))
        self.label_5.setObjectName("label_5")
        self.retry = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.retry.setGeometry(QtCore.QRect(120, 360, 41, 21))
        self.retry.setProperty("value", 3)
        self.retry.setObjectName("retry")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(300, 320, 31, 21))
        self.label_6.setObjectName("label_6")
        self.log = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.log.setGeometry(QtCore.QRect(320, 321, 61, 20))
        self.log.setObjectName("log")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(340, 360, 41, 20))
        self.label_7.setObjectName("label_7")
        self.stdout = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.stdout.setGeometry(QtCore.QRect(210, 320, 101, 21))
        self.stdout.setObjectName("stdout")
        self.timeout = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.timeout.setGeometry(QtCore.QRect(380, 360, 41, 21))
        self.timeout.setProperty("value", 3)
        self.timeout.setObjectName("timeout")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(170, 360, 51, 21))
        self.label_8.setObjectName("label_8")
        self.worker = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.worker.setGeometry(QtCore.QRect(210, 360, 41, 21))
        self.worker.setProperty("value", 1)
        self.worker.setObjectName("worker")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(260, 360, 51, 21))
        self.label_9.setObjectName("label_9")
        self.download_num = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.download_num.setGeometry(QtCore.QRect(300, 360, 31, 21))
        self.download_num.setProperty("value", 5)
        self.download_num.setObjectName("download_num")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(430, 360, 61, 21))
        self.label_10.setObjectName("label_10")
        self.download_delay = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.download_delay.setGeometry(QtCore.QRect(480, 360, 41, 21))
        self.download_delay.setProperty("value", 1)
        self.download_delay.setObjectName("download_delay")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(510, 320, 72, 21))
        self.label_11.setObjectName("label_11")
        self.task = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.task.setGeometry(QtCore.QRect(550, 320, 91, 21))
        self.task.setText("")
        self.task.setObjectName("task")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(-5, 1, 791, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 762, 526))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.getheaders = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.getheaders.setGeometry(QtCore.QRect(20, 10, 300, 400))
        self.getheaders.setObjectName("getheaders")
        self.addheader = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.addheader.setGeometry(QtCore.QRect(400, 10, 300, 400))
        self.addheader.setObjectName("addheader")
        self.start_headers = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.start_headers.setGeometry(QtCore.QRect(310, 480, 93, 28))
        self.start_headers.setObjectName("start_headers")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 762, 526))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.getheaders_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.getheaders_2.setGeometry(QtCore.QRect(40, 50, 300, 400))
        self.getheaders_2.setObjectName("getheaders_2")
        self.getheaders_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.getheaders_3.setGeometry(QtCore.QRect(430, 50, 300, 400))
        self.getheaders_3.setObjectName("getheaders_3")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setGeometry(QtCore.QRect(420, 20, 31, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 20, 113, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请求网站"))
        self.label_2.setText(_translate("Dialog", "请求参数"))
        self.label_3.setText(_translate("Dialog", "请求头"))
        self.start.setText(_translate("Dialog", "启动"))
        self.check_cookie.setText(_translate("Dialog", "检测cookie"))
        self.datas.setHtml(_translate("Dialog",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                      "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.url.setHtml(_translate("Dialog",
                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                    "p, li { white-space: pre-wrap; }\n"
                                    "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                    "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.post.setText(_translate("Dialog", "Post"))
        self.encode.setText(_translate("Dialog", "utf-8"))
        self.label_4.setText(_translate("Dialog", "编码方式"))
        self.verify.setText(_translate("Dialog", "Verify"))
        self.label_5.setText(_translate("Dialog", "Retry"))
        self.label_6.setText(_translate("Dialog", "Log"))
        self.log.setText(_translate("Dialog", "info"))
        self.label_7.setText(_translate("Dialog", "Timeout"))
        self.stdout.setText(_translate("Dialog", "日志重定向"))
        self.label_8.setText(_translate("Dialog", "线程数"))
        self.label_9.setText(_translate("Dialog", "下载数"))
        self.label_10.setText(_translate("Dialog", "下载延迟"))
        self.label_11.setText(_translate("Dialog", "任务名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "请求测试"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "网站"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "状态码"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "请求体"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "响应内容"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "源码查看"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "任务列表"))
        self.start_headers.setText(_translate("Dialog", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "headers"))
        self.label_12.setText(_translate("Dialog", "密钥"))
        self.label_13.setText(_translate("Dialog", "pan\'y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "加解密"))
        """开始"""
        for i in range(10):
            row_count = self.tableWidget.rowCount()  # 返回当前行数(尾部)
            self.tableWidget.insertRow(row_count)
            self.tableWidget.setItem(row_count, 0, QtWidgets.QTableWidgetItem(str(i)))
            self.tableWidget.setItem(row_count, 1, QtWidgets.QTableWidgetItem(
                'https://wenku.csdn.net/answer/b54409d5a931b319cba4b4eec08a4783?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522168239358116800182143967%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=168239358116800182143967&biz_id=&utm_medium=distribute.pc_search_result.none-task-chatgpt-2~all~first_rank_ecpm_v1~rank_v31_ecpm-5-b54409d5a931b319cba4b4eec08a4783-null-null.142^v86^insert_down38v5,239^v2^insert_chatgpt&utm_term=pyqt%20tablewidget%E6%8F%92%E5%85%A5%E6%95%B0%E6%8D%AE&spm=1018.2226.3001.4187'))
            self.tableWidget.setItem(row_count, 2, QtWidgets.QTableWidgetItem('2'))
            self.tableWidget.setItem(row_count, 3, QtWidgets.QTableWidgetItem('3'))
            self.view_start = QtWidgets.QPushButton('查看')
            self.view_start.clicked.connect(partial(self.start_view, row_count))
            self.tableWidget.setCellWidget(row_count, 5, self.view_start)

        self.start.clicked.connect(self.start_btn)
        self.start_headers.clicked.connect(self.start_headers_btn)
        self.tableWidget.cellPressed.connect(self.getPosContent)

    def start_btn(self):
        from PrSpider_run import Spider
        url = self.url.toPlainText()
        data = self.datas.toPlainText()
        header = self.header_2.toPlainText()
        encode = self.encode.text()
        retry = self.retry.text()
        log = self.log.text()
        task = self.task.text()
        download_delay = self.download_delay.text()
        download_num = self.download_num.text()
        timeout = self.timeout.text()
        verify = self.verify.isChecked()
        post = self.post.isChecked()
        stdout = self.stdout.isChecked()
        stdout = True if stdout else False
        method = 'POST' if post else 'GET'
        print(
            'url', url,
            'data', data,
            'headers', header,
            'post', post,
            'encode', encode,
            'verify', verify,
            'retry', retry,
            'log', log,
            'task', task,
            'download_delay', download_delay,
            'download_num', download_num,
            'timeout', timeout,
            'stdout', stdout,
        )
        Spider(
            url=url, verify=verify, retry=retry, method=method, header=header, encode=encode,
            stdout=stdout, log=log, timeout=timeout, download_delay=download_delay, download_num=download_num,
        )

    def start_headers_btn(self):
        import json, re
        h_str = '{\n'
        headers = self.getheaders.toPlainText()
        if headers:
            headers = re.sub(':\s+', ':', headers)
            headers = headers.replace('：', ':').replace(':\n', ':').replace(': ', ':')
            # hdic = {}
            headers = re.findall('(.*?):(.*)', headers)
            for query in headers:
                k = query[0].replace('"', '\\"')
                v = query[1].replace('"', '\\"')
                h_str += f"""  "{k}": "{v}", \n"""
        h_str += '}'
        self.addheader.setPlainText(h_str)

    def start_view(self, row, rol):
        from w2 import UiMainTwo
        content = self.tableWidget.item(row, 0).text()
        self.ui_2 = UiMainTwo(title='源码-' + str(content), text='test')
        self.ui_2.show()

    def getPosContent(self, row, col):
        try:
            content = self.tableWidget.item(row, col).text()
            print("选中行：" + str(row))
            print("选中列：" + str(col))
            print('选中内容:' + content)
        except:
            pass


class Child(QWidget):
    def __init__(self, content):
        super().__init__()
        self.setWindowTitle(content)
